#pragma once

// --- Versiune GLSL in functie de platforma ---
#ifdef __EMSCRIPTEN__
    #define GLSL_VERSION "#version 300 es\nprecision highp float;\n"
#else
    #define GLSL_VERSION "#version 330 core\n"
#endif

// --- 1. VERTEX SHADER ---
static const char *vertexShaderSource = GLSL_VERSION
    "layout (location = 0) in vec2 aPos;\n"
    "layout (location = 1) in float aPhi;\n"
    "layout (location = 2) in vec2 aSize;\n"
    "layout (location = 3) in float aType;\n"
    "layout (location = 4) in vec4 aColor;\n"
    "layout (location = 5) in float aFiltru;\n"
    "layout (location = 6) in vec3 aVel;\n"
    "layout (location = 7) in vec3 aAcc;\n"

    "out VS_OUT {\n"
    "    float phi;\n"
    "    vec2 size;\n"
    "    float type;\n"
    "    vec4 color;\n"
    "    float filtru;\n"
    "    vec3 vVel;\n"
    "    vec3 vAcc;\n"
    "} vs_out;\n"

    "void main() {\n"
    "   gl_Position = vec4(aPos, 0.0, 1.0);\n"
    "   vs_out.phi = aPhi;\n"
    "   vs_out.size = aSize;\n"
    "   vs_out.type = aType;\n"
    "   vs_out.color = aColor;\n"
    "   vs_out.filtru = aFiltru;\n"
    "   vs_out.vVel = aVel;\n"
    "   vs_out.vAcc = aAcc;\n"
    "}\0";

// --- 2. GEOMETRY SHADER ---
static const char *geometryShaderSource = GLSL_VERSION
    "layout (points) in;\n"
    "layout (triangle_strip, max_vertices = 4) out;\n"

    "in VS_OUT {\n"
    "    float phi; vec2 size; float type; vec4 color; float filtru; vec3 vVel; vec3 vAcc;\n"
    "} gs_in[];\n"

    "out vec3 TexCoord;\n"
    "out float ShapeType;\n"
    "out vec4 fColor;\n"
    "out float filtru;\n"
    "out float fSens;\n"
    "out vec3 fVel; out vec3 fAcc; out vec2 fLocalPos; out vec2 fGlobalPos;\n"

    "uniform float scale; uniform vec2 cameraOffset; uniform float aspect_ratio;\n"

    "void main() {\n"
    "    if(gs_in[0].type < 0.5) return;\n"

    "    float rot_phi = (gs_in[0].type > 6.5 && gs_in[0].type < 7.5) ? 0.0 : gs_in[0].phi;\n"
    "    mat2 rot = mat2(cos(rot_phi), sin(rot_phi), -sin(rot_phi), cos(rot_phi));\n"
    "    vec2 center = gl_in[0].gl_Position.xy - cameraOffset;\n"

    "    ShapeType = gs_in[0].type;\n"
    "    fColor = gs_in[0].color;\n"
    "    filtru = gs_in[0].filtru;\n"
    "    fSens = gs_in[0].phi;\n"
    "    fVel = gs_in[0].vVel; fAcc = gs_in[0].vAcc;\n"

    "    float expand = (filtru > 0.5 && ShapeType < 3.5) ? 1.15 : 1.0;\n"
    "    vec2 halfSize;\n"

    "    if (ShapeType > 3.5 && ShapeType < 4.5) {\n"
    "        halfSize = vec2(gs_in[0].size.x / 2.0, 0.15);\n"
    "    } else if (ShapeType > 6.5 && ShapeType < 7.5) {\n"
    "        halfSize = vec2(gs_in[0].size.x + gs_in[0].size.y);\n"
    "    } else {\n"
    "        halfSize = (gs_in[0].size / 2.0) * expand;\n"
    "    }\n"

    "    vec2 offsets[4] = vec2[](vec2(-halfSize.x, -halfSize.y), vec2(halfSize.x, -halfSize.y), vec2(-halfSize.x, halfSize.y), vec2(halfSize.x, halfSize.y));\n"
    "    vec2 uvs[4] = vec2[](vec2(-1.0, -1.0)*expand, vec2(1.0, -1.0)*expand, vec2(-1.0, 1.0)*expand, vec2(1.0, 1.0)*expand);\n"

    "    for(int i=0; i<4; i++) {\n"
    "        fLocalPos = offsets[i] / expand;\n"
    "        vec2 pos = center + rot * offsets[i];\n"
    "        fGlobalPos = gl_in[0].gl_Position.xy + rot * offsets[i];\n"
    "        gl_Position = vec4((pos.x * scale)/aspect_ratio, pos.y * scale, 0.0, 1.0);\n"
    "        TexCoord = vec3(uvs[i], gs_in[0].size.y);\n"
    "        EmitVertex();\n"
    "    }\n"
    "    EndPrimitive();\n"
    "}\0";

// --- 3. FRAGMENT SHADER ---
static const char *fragmentShaderSource = GLSL_VERSION
    "out vec4 FragColor;\n"
    "in vec3 TexCoord; in float ShapeType; in vec4 fColor; in float filtru;\n"
    "in float fSens;\n"
    "in vec3 fVel; in vec3 fAcc; in vec2 fLocalPos; in vec2 fGlobalPos;\n"

    "uniform int ViewMode;\n"

    "void main() {\n"
    "   vec4 outputColor = fColor;\n"
    "   bool inBorder = false;\n"
    "   bool isHovered = (filtru > 0.5 && filtru < 1.5) || (filtru > 2.5);\n"
    "   bool isSelected = (filtru > 1.5);\n"
    "   float raza_curenta = isHovered ? 1.06 : 1.0;\n"
    "   float grosime_margine = 0.08;\n"

    "   if(ShapeType < 1.5) {\n"
    "       float d = length(TexCoord.xy);\n"
    "       if (d > raza_curenta + (isSelected ? grosime_margine : 0.0)) discard;\n"
    "       if (isSelected && d > raza_curenta) {\n"
    "           outputColor = vec4(1.0, 1.0, 1.0, 1.0);\n"
    "           inBorder = true;\n"
    "       }\n"
    "   }\n"
    "   else if (ShapeType > 1.5 && ShapeType < 3.5 ) {\n"
    "       float d = max(abs(TexCoord.x), abs(TexCoord.y));\n"
    "       if (d > raza_curenta + (isSelected ? grosime_margine : 0.0)) discard;\n"
    "       if (isSelected && d > raza_curenta) {\n"
    "           outputColor = vec4(1.0, 1.0, 1.0, 1.0);\n"
    "           inBorder = true;\n"
    "       }\n"
    "   }\n"
    "   else if (ShapeType > 3.5 && ShapeType < 4.5) {\n"
    "       float l_0 = TexCoord.z;\n"
    "       float spire = l_0 * 8.0;\n"
    "       float unda = sin(TexCoord.x * 3.1415 * spire) * (1.0 - TexCoord.x * TexCoord.x);\n"
    "       if(abs(TexCoord.y - unda) > 0.35) discard;\n"
    "   }\n"
    "   else if (ShapeType > 4.5 && ShapeType < 5.5){\n"
    "       float x = TexCoord.x;\n"
    "       float y = abs(TexCoord.y);\n"
    "       float start_varf = 0.5;\n"
    "       float grosime_coada = 0.35;\n"
    "       if(x < start_varf){\n"
    "           if(y > grosime_coada) discard;\n"
    "       } else {\n"
    "           float factor_panta = (x - start_varf) / (1.0 - start_varf);\n"
    "           if(y > (1.0 - factor_panta)) discard;\n"
    "       }\n"
    "   }\n"
    "   else if (ShapeType > 5.5 && ShapeType < 6.5){\n"
    "       vec2 pA = fVel.xy;\n"
    "       vec2 pB = fAcc.xy;\n"
    "       float burta = fVel.z;\n"
    "       vec2 fir_dir = pB - pA;\n"
    "       float L = length(fir_dir);\n"
    "       float t = clamp(dot(fGlobalPos - pA, fir_dir) / (L * L + 0.00001), 0.0, 1.0);\n"
    "       float offset_y = burta * 4.0 * t * (1.0 - t);\n"
    "       vec2 punct_pe_curba = pA + fir_dir * t + vec2(0.0, -offset_y);\n"
    "       float dist_la_fir = length(fGlobalPos - punct_pe_curba);\n"
    "       float grosime_fir = 0.05;\n"
    "       if(dist_la_fir > grosime_fir + (isSelected ? grosime_margine : 0.0)) discard;\n"
    "       if(isSelected && dist_la_fir > grosime_fir) {\n"
    "           outputColor = vec4(1.0, 1.0, 1.0, 1.0);\n"
    "           inBorder = true;\n"
    "       }\n"
    "   }\n"
    "   else if (ShapeType > 6.5 && ShapeType < 7.5) {\n"
    "       float r = length(TexCoord.xy);\n"
    "       vec2 uv_head = TexCoord.xy - vec2(0.0, 0.65);\n"
    "       bool is_ccw = (fSens > 0.0);\n"
    "       bool in_head_ccw = (uv_head.x > 0.0 && uv_head.x < 0.25 && abs(uv_head.y) < uv_head.x * 1.2);\n"
    "       bool in_head_cw  = (uv_head.x < 0.0 && uv_head.x > -0.25 && abs(uv_head.y) < -uv_head.x * 1.2);\n"
    "       bool in_ring = (r > 0.55 && r < 0.75);\n"
    "       bool in_gap_ccw = (TexCoord.x < 0.0 && TexCoord.y > 0.0);\n"
    "       bool in_gap_cw = (TexCoord.x > 0.0 && TexCoord.y > 0.0);\n"
    "       if (is_ccw) {\n"
    "           if (in_gap_ccw) discard;\n"
    "           if (!in_ring && !in_head_ccw) discard;\n"
    "       } else {\n"
    "           if (in_gap_cw) discard;\n"
    "           if (!in_ring && !in_head_cw) discard;\n"
    "       }\n"
    "   }\n"

    "   if (ViewMode == 0 || ShapeType > 3.5) {\n"
    "       FragColor = outputColor;\n"
    "       return;\n"
    "   }\n"

    "   float mag = 0.0;\n"
    "   if (ViewMode == 1) {\n"
    "       vec2 vM = fVel.xy + vec2(-fVel.z * fLocalPos.y, fVel.z * fLocalPos.x);\n"
    "       mag = length(vM);\n"
    "   } else if (ViewMode == 2) {\n"
    "       vec2 a_tang = vec2(-fAcc.z * fLocalPos.y, fAcc.z * fLocalPos.x);\n"
    "       vec2 a_norm = -(fVel.z * fVel.z) * fLocalPos;\n"
    "       mag = length(fAcc.xy + a_tang + a_norm);\n"
    "   }\n"

    "   float t = clamp(mag / (ViewMode == 1 ? 20.0 : 150.0), 0.0, 1.0);\n"
    "   vec3 heat = (t < 0.5) ? mix(vec3(0.1, 0.3, 0.8), vec3(1.0, 0.8, 0.0), t*2.0) : mix(vec3(1.0, 0.8, 0.0), vec3(1.0, 0.0, 0.0), (t-0.5)*2.0);\n"
    "   if (inBorder) {\n"
    "       FragColor = vec4(1.0, 1.0, 1.0, outputColor.a);\n"
    "   } else {\n"
    "       FragColor = vec4(heat, outputColor.a);\n"
    "   }\n"
    "}\0";

// --- 4. GRID VERTEX SHADER ---
static const char *gridVertexShaderSource = GLSL_VERSION
    "layout (location = 0) in vec2 aPos;\n"
    "out vec2 WorldPos;\n"
    "uniform vec2 cameraOffset;\n"
    "uniform float zoom;\n"
    "uniform float aspect_ratio;\n"
    "void main() {\n"
    "    gl_Position = vec4(aPos, 0.0, 1.0);\n"
    "    WorldPos = vec2(aPos.x * aspect_ratio * zoom + cameraOffset.x, aPos.y * zoom + cameraOffset.y);\n"
    "}\0";

// --- 5. GRID FRAGMENT SHADER ---
static const char *gridFragmentShaderSource = GLSL_VERSION
    "out vec4 FragColor;\n"
    "in vec2 WorldPos;\n"
    "uniform float zoom;\n"
    "void main() {\n"
    "    vec2 grid = fract(WorldPos);\n"
    "    float grosime = 0.0030 * zoom;\n"
    "    vec4 color = vec4(0.0);\n"
    "    if (grid.x < grosime || grid.y < grosime) {\n"
    "        color = vec4(0.3, 0.3, 0.3, 0.2);\n"
    "    }\n"
    "    if (abs(WorldPos.x) < grosime) color = vec4(0.8, 0.8, 0.8, 0.2);\n"
    "    if (abs(WorldPos.y) < grosime) color = vec4(0.8, 0.8, 0.8, 0.2);\n"
    "    if (color.a == 0.0) discard;\n"
    "    FragColor = color;\n"
    "}\0";